version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: vasuj
      POSTGRES_PASSWORD: Vasu123
      POSTGRES_DB: urlshort
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"